{% set name = "pulp" %}
{% set version = "3.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7eb99b9ce7beeb8bbb7ea9d1c919f02f003ab7867e0d1e322f2f2c26dd31c8ba
  patches:
    - patches/0001-Use-coin-or-cbc-from-the-env.patch  # [not win]

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    # Remove bundled cbc binaries, using coin-or-cbc provided cbc instead:
    - rm -rf "${SP_DIR}/pulp/solverdir/cbc"  # [not win]
  entry_points:
    - pulptest = pulp.tests.run_tests:pulpTestAll
  missing_dso_whitelist:
  # for cbc binaries
    - /lib64/libpthread.so.0  # [linux]
    - /lib64/librt.so.1       # [linux]
    - /lib64/libdl.so.2       # [linux]
    - lib/libgcc_s.so.1       # [linux]
    - lib/libstdc++.so.6      # [linux]
    - /lib64/libm.so.6        # [linux]
    - /lib64/libc.so.6        # [linux]
    - $RPATH/libpthread.so.0  # [linux]
    - $RPATH/librt.so.1       # [linux]
    - $RPATH/libm.so.6        # [linux]
    - $RPATH/libc.so.6        # [linux]
    - $RPATH/libdl.so.2       # [linux]
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=77
    - coin-or-cbc  # [not win]
    # We use glpk on Windows because coincbc produces conflict on Windows.
    - glpk  # [win]
  run:
    - python

test:
  imports:
    - pulp
    - pulp.solverdir
    - pulp.apis
    - pulp.constants
    - pulp.pulp
    - pulp.sparse
    - pulp.tests
    - pulp.utilities
  commands:
    - pip check
    - python -c "import pulp; assert pulp.LpSolverDefault, 'default solver not available'"
    - pulptest
  requires:
    - pip
    - coin-or-cbc  # [not win]
    - glpk  # [win]

about:
  home: https://github.com/coin-or/pulp
  summary: |
    PuLP is an LP modeler written in python. PuLP can generate MPS or LP files
    and call GLPK, COIN CLP/CBC, CPLEX, and GUROBI to solve linear problems.
  description: |
    PuLP is an linear and mixed integer programming modeler written in Python. 
    With PuLP, it is simple to create MILP optimisation problems and solve
    them with the latest open-source (or proprietary) solvers. PuLP can
    generate MPS or LP files and call solvers such as GLPK, COIN-OR CLP/CBC,
    CPLEX, GUROBI, MOSEK, XPRESS, CHOCO, MIPCL, HiGHS, SCIP/FSCIP.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://coin-or.github.io/pulp
  dev_url: https://github.com/coin-or/pulp

extra:
  recipe-maintainers:
    - johanneskoester
    - christopher-schroeder
    - venaturum
