{% set name = "pulp" %}
{% set version = "2.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e30e6c0ef2c0edac185220e3e53faca62eb786a9bd68465208f05bc63e850f3

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - rm "${SP_DIR}/pulp/solverdir/CoinMP.dll"  # [not win]
  entry_points:
    - pulptest = pulp.tests.run_tests:pulpTestAll

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    # We use glpk on Windows because coincbc produces conflict on Windows.
    - coincbc  # [not win]
    - glpk  # [win]

test:
  imports:
    - pulp
    - pulp.solverdir
  commands:
    - pip check
    - python -c "import pulp; assert pulp.LpSolverDefault, 'default solver not available'"
    - pulptest
  requires:
    - pip
    - glpk  # [not s390x]

about:
  home: https://github.com/coin-or/pulp
  summary: |
    PuLP is an LP modeler written in python. PuLP can generate MPS or LP files
    and call GLPK, COIN CLP/CBC, CPLEX, and GUROBI to solve linear problems.
  description: |
    PuLP is an LP modeler written in python. PuLP can generate MPS or LP files
    and call GLPK, COIN CLP/CBC, CPLEX, and GUROBI to solve linear problems.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://coin-or.github.io/pulp/
  dev_url: https://github.com/coin-or/pulp

extra:
  recipe-maintainers:
    - johanneskoester
    - christopher-schroeder
    - venaturum
