travis:
  secure:
    BINSTAR_TOKEN: uqDk1wJ6QjU77c7vFKsuwLidBWxwjx62eu16WveBiIq95solzFJmnhvuTiClKrVkuF3tV4rkGuqaeI+GhrAg/shGLYlM4tFcLasGAguvCeSbWGoufOMkzlHTUAV0RxJ3UNi6RBu32mhI1mb0fPk6/zKCPgLBoQqYTe6EDOG6EDmPR8py1wynWd0B7j3h2a+GfoYuE1RJMBKn2dwYI5GkxXJqKAzRblgoaL4zcGeixu/oRRl4+8QuXuac7hCMzJ/KJxUGkua+eCZy50tvdQrgbbBo9zQ7SK8ThKDeKWAQtj7ZIG0X2P6C/bmWSAI52DymUzCvFBLMirhOp2XdTWDBp8OsR+Em0+PkE4hmwFr6OP11C0aJqOv8azM1nSot1L1ntNQ0o2T0VZpWfdf661xLKauJ2tve5/OscA2otutiBvsS4/KX7FmQ4FbJP9J1ssc5td1VaEG84MIDJ2JcYl3ENTNNr/3eq5GHMP5ZO6JQw1IjJpNo9A6S2XcSuNMAMN10LyWUE2Vk8bWMconu1Hqq0TWctY3oiHOFViVUfR8h2Y/P9MoHvkP4otFe/1W8OU5fZGsYiXrRJLupPKTaEQhLNNbBpAaZw4Smhde1nWtAD5UORAX068FbuB6xHpLd4d3f3lVkQZ5vS2HpDqeg7J+8PAVb+oQNZgEGVZCj/hBrY4w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
